# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2023, E36 Knots

[package]
name = "ash"
description = "Ash Rust SDK"
version = "0.1.0"
authors = ["E36 Knots"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/AshAvalanche/ash-rs"
license = "BSD-3-Clause"
keywords = ["blockchain", "avalanche", "sdk", "rust", "ash"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avalanche-types = "0.0.203"
clap = { version = "4.0.32", features = ["derive"] }
hex = "0.4.3"
regex = "1.7.1"
serde = "1.0.152"
serde_json = "1.0.91"
