# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2023, E36 Knots

[package]
name = "ash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avalanche-types = "0.0.203"
