# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2023, E36 Knots

---
avalancheNetworks:
  - name: mainnet
    subnets:
      - id: 11111111111111111111111111111111LpoYY
        controlKeys: []
        threshold: 0
        blockchains:
          - id: 2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5
            name: C-Chain
            vmType: EVM
            rpcUrl: https://api.avax.network/ext/bc/C/rpc
  - name: fuji
    subnets:
      - id: 11111111111111111111111111111111LpoYY
        controlKeys: []
        threshold: 0
        blockchains:
          - id: yH8D7ThNJkxmtkuv2jgBa4P1Rn3Qpr4pPr7QYNfcdoS6k6HWp
            name: C-Chain
            vmType: EVM
            rpcUrl: https://api.avax-test.network/ext/bc/C/rpc
