[target.aarch64-unknown-linux-gnu]
ar = "aarch64-linux-gnu-ar"
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin21.4-clang"
ar = "x86_64-apple-darwin21.4-ar"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin21.4-clang"
ar = "aarch64-apple-darwin21.4-ar"
