---
name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Template tests config file
        run: |
          envsubst < crates/ash/tests/conf/quicknode.yml > ${{ runner.temp }}/ash-test-avax-conf.yml
        env:
          ASH_QUICKNODE_FUJI_ENDPOINT: ${{ secrets.ASH_QUICKNODE_FUJI_ENDPOINT }}
          ASH_QUICKNODE_FUJI_TOKEN: ${{ secrets.ASH_QUICKNODE_FUJI_TOKEN }}

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          AVAX_TEST_AVAX_CONFIG: ${{ runner.temp }}/ash-test-avax-conf.yml
